name: ttplayers delpoy pipeline
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'feature/**'

jobs:
  prod_build_deploy:
      runs-on: ubuntu-latest
      environment: prod
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16.14.0'
        - run: npm install
        - run: npm install -g @angular/cli
        - run: ng build --prod --progress --output-path=public
        - uses: FirebaseExtended/action-hosting-deploy@v0
          with:
            repoToken: '${{ secrets.GITHUB_TOKEN }}'
            firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TTPLAYERS }}'
            channelId: live
            projectId: ttplayers-c589c
          env:
            FIREBASE_CLI_PREVIEWS: hostingchannels