
version: "3.9"
services:
    mongodb:
        container_name: tt-mongo-db
        image: mongo:latest
        volumes:
            - mongodb_volumes:/data/mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass
        ports:
            - 27017:27017
        networks:
            - mongodb_nework

volumes:
    mongodb_volumes:

networks:
    mongodb_nework:
