//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TtPlayers.Importer.data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SndttaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SndttaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TtPlayers.Importer.data.SndttaResource", typeof(SndttaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name, ShortName
        ///Annangrove Next Time,AnnaNext
        ///Annangrove Winners,AnnaWin
        ///Cherrybrook Fighter,CherFig
        ///Cherrybrook Nadassi IX,CherIX
        ///Cherrybrook Junior,CherJun
        ///Cherrybrook Nadassi VIII,CherVIII
        ///Forestville Eagles,ForEag
        ///Forest Gump,ForGump
        ///Forestville King Pong,ForKP
        ///Forest Owlet,ForOwl
        ///Forestville Pioneers,ForPion
        ///Forest Rising,ForRis
        ///Forestville Spin Koala,ForSK
        ///Forestville Woodchucks,ForWood
        ///Hornsby Black,HornBl
        ///Hornsby Orange,HornOr
        ///JJW Champions,JJWCham
        ///JJW Heroes,JJWHero
        ///JJW Samurai,J [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string teamName {
            get {
                return ResourceManager.GetString("teamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round,Day,Date,Time,Age Grp,Division,Blank1,Home Team,Vs.,Away Team,Blank2,Location, 
        ///11,Mon,9th Oct &apos;23, ,OPEN1,Premier, ,MacPrem,Vs.,Bye, ,Bye, 
        ///11,Mon,9th Oct &apos;23,19:00,OPEN1,Div 1, ,MacPir,Vs.,PymLS, ,MAC1, 
        ///11,Mon,9th Oct &apos;23,19:00,OPEN1,Div 1, ,MacSmas,Vs.,HornBl, ,MAC1, 
        ///11,Mon,9th Oct &apos;23,19:30,OPEN1,Premier, ,JJWCham,Vs.,SUNSAv, ,JJW1, 
        ///11,Mon,9th Oct &apos;23,20:00,OPEN1,Div 3, ,RTTCD3,Vs.,SUNSCh, ,RTTC1, 
        ///11,Tue,10th Oct &apos;23,19:00,OPEN1,Div 5, ,MacAdv,Vs.,SUNSEver, ,MAC1, 
        ///11,Tue,10th Oct &apos;23,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Upcoming {
            get {
                return ResourceManager.GetString("Upcoming", resourceCulture);
            }
        }
    }
}
